# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'jx-release-version'
description: 'https://github.com/jenkins-x-plugins/jx-release-version'
branding:
  icon: 'tag'  
  color: 'blue'
inputs:
  previous-version:
    description: 'The strategy to detect the previous version: auto, from-tag, from-file or manual'
    required: false
    default: 'auto'
  next-version:
    description: 'The strategy to calculate the next version: auto, semantic, from-file, increment or manual'
    required: false
    default: 'auto'
  output-format:
    description: 'The output format of the next version'
    required: false
    default: '{{.Major}}.{{.Minor}}.{{.Patch}}'
  tag:
    description: 'If enabled, a new tag will be created'
    required: false
    default: 'false'
  tag-prefix:
    description: 'The prefix for the new tag - prefixed before the output'
    required: false
    default: 'v'
  push-tag:
    description: 'If enabled, the new tag will be pushed to the `origin` remote'
    required: false
    default: 'true'
  github-token:
    description: 'The github token used to push the tag'
    required: false
    default: ''
  git-user:
    description: 'If you want to override the name of the author/committer of the tag'
    required: false
    default: ''
  git-email:
    description: 'If you want to override the email of the author/committer of the tag'
    required: false
    default: ''
outputs:
  version:
    description: 'The next release version'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/jenkins-x/jx-release-version:2.5.1'
  entrypoint: 'github-actions-entrypoint.sh'
  env:
    PREVIOUS_VERSION: ${{ inputs.previous-version }}
    NEXT_VERSION: ${{ inputs.next-version }}
    OUTPUT_FORMAT: ${{ inputs.output-format }}
    TAG: ${{ inputs.tag }}
    TAG_PREFIX: ${{ inputs.tag-prefix }}
    PUSH_TAG: ${{ inputs.push-tag }}
    GIT_TOKEN: ${{ inputs.github-token }}
    GIT_NAME: ${{ inputs.git-user }}
    GIT_EMAIL: ${{ inputs.git-email }}