// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import model "github.com/jenkins-x/jx-release-version/domain"

// GitClient is an autogenerated mock type for the GitClient type
type GitClient struct {
	mock.Mock
}

// ListTags provides a mock function with given fields: ctx, owner, repo
func (_m *GitClient) ListTags(ctx context.Context, owner string, repo string) ([]model.Tag, error) {
	ret := _m.Called(ctx, owner, repo)

	var r0 []model.Tag
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []model.Tag); ok {
		r0 = rf(ctx, owner, repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Tag)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, owner, repo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
